In [1]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])
(a)

array([1, 2, 3, 4])

In [12]:
print('size a :',a.size)
print('dim of a:',a.ndim)
print(a)
print('datatype:',a.dtype)

size a : 4
dim of a: 1
[1 2 3 4]
datatype: int32


In [20]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('',b.shape)
print('',b.ndim)
print('',b)

 (3, 3)
 2
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
b = np.array([
              [[1,2],
               [3,4],
               [5,6]],
      
               [[3,4],
                [5,3],
                [7,8],]])
print('',b)b = np.array([[[2,4,9],[3,6,7]],
              [[6,8,10],[13,16,17]],
             [[12,14,19],[23,26,27]]])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)
print('Dimension:',b.ndim)
print("shape:",b.shape)

 [[[1 2]
  [3 4]
  [5 6]]

 [[3 4]
  [5 3]
  [7 8]]]
Dimension: 3
shape: (2, 3, 2)


In [75]:
d = np.array([[[2,4,9],[3,6,7]],
              [[6,8,10],[13,16,17]],
             [[12,14,19],[23,26,27]]])
print(d.ndim)
print(d.shape)
print(d.dtype)

3
(3, 2, 3)
float64


In [72]:
# (3,3,3)

c = np.array([ 
              [[1,2,3],
               [4,5,6],
               [7,8,9]],
               
              [[3,2,1],
               [4,2,1],
               [9,0,1]],
    
              [[1,3,4],
               [3,1,5],
               [6,9,1]]])

In [68]:
print(c)
print('Dimension:',c.ndim)
print("shape:",c.shape)
print('datatype:',c.dtype)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 2 1]
  [4 2 1]
  [9 0 1]]

 [[1 3 4]
  [3 1 5]
  [6 9 1]]]
Dimension: 3
shape: (3, 3, 3)
datatype: int32


# Arange and Reshape

In [43]:
d = np.arange(8)
d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
d = np.arange(30).reshape(5,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [42]:
d = np.arange(6).reshape(1,1,1,1,1,6)
print(d)
print('Dimension:',d.ndim)
print("shape:",d.shape)
print('datatype:',d.dtype)

[[[[[[0 1 2 3 4 5]]]]]]
Dimension: 6
shape: (1, 1, 1, 1, 1, 6)
datatype: int32


In [49]:
d = np.arange(10).reshape(1,1,1,1,1,1,1,1,1,1,10)
print(d)
print('Dimension:',d.ndim)
print("shape:",d.shape)
print('datatype:',d.dtype)

[[[[[[[[[[[0 1 2 3 4 5 6 7 8 9]]]]]]]]]]]
Dimension: 11
shape: (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10)
datatype: int32


In [52]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [56]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# Linspace - Which gives the equally spaced netween two numbers

In [57]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [60]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

# Ravel - converts to single dimension

In [78]:
f = np.arange(10).reshape(2,5)
f

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
f.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
f = np.arange(10).reshape(5,1,2)
f = np.array([
              [[1,2]],
              [[3,4]],
              [[5,6]],
              [[7,8]],
              [[9,10],]
])
print("",f)
print('dim of f',f.ndim)

 [[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]]
dim of f 3


In [94]:
g = f.ravel()

In [96]:
print('Shape of Ravel:',g.shape)
print("ndim:",g.ndim)

Shape of Ravel: (10,)
ndim: 1


# Random numbers , random function

In [118]:
h = np.random.rand() # gets a random VALUE b/w 0 and 1 
h

0.45190506157330756

In [133]:
np.random.rand()*100

34.14632607866533

In [142]:
int((np.random.rand())*100)

17

In [152]:
(np.random.randint(25,50))

33

In [167]:
np.sqrt((np.random.randint(3,4)))

1.7320508075688772

In [169]:
np.sqrt(4)

2.0

In [172]:
np.round(4.2) #Round off to the nearest value

4.0

In [173]:
np.round(5.6)

6.0

In [176]:
np.floor(4.2) #Floor actually roundoff to the lowest value

4.0

In [175]:
np.floor(4.8)

4.0

In [179]:
np.ceil(4.2) # Ceil wilL ACTUALLY ROUNDOFF to the highest value

5.0

In [180]:
np.ceil(5.8)

6.0

In [182]:
np.ceil(5.1)

6.0

In [184]:
np.random.rand(1,10).reshape(5,1,2)

array([[[0.66969754, 0.34818838]],

       [[0.4018906 , 0.3122407 ]],

       [[0.00361586, 0.50348533]],

       [[0.42266565, 0.53502929]],

       [[0.93679842, 0.54100445]]])

In [195]:
(np.random.randint(1,10))

3

# Horizontal and Vertical Split

In [197]:
i = np.arange(32).reshape(4,8)
i

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [206]:
np.hsplit(i,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]), array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [207]:
np.vsplit(i,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

In [209]:
np.hsplit(i,2)[1]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [210]:
np.vsplit(i,2)[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

# Horizontal Stack and Vertical Stack (Joining the Two matices)

In [219]:
j = np.arange(15,30).reshape(3,5)
k = np.arange(15).reshape(3,5)
print(j)
print(k)

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [220]:
np.hstack((k,j))

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [221]:
np.vstack((k,j))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

# addition of two elements in a array an type cast to float

In [223]:
l = np.array([1+2,4+4,6+6,15],dtype='float')
l

array([ 3.,  8., 12., 15.])

In [229]:
m = np.array([3+2,4,1,1],dtype='int')
n = np.array(m[0]+[1],dtype='float')
print(m)
print(n)
print(n.dtype)
print(m.dtype)

[5 4 1 1]
[6.]
float64
int32
